x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.1-python3.11
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__BASE_URL: http://0.0.0.0:8088
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8088
    AIRFLOW__CORE__LOGGING_LEVEL: INFO
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Singapore
  volumes:
    - ./src/dags:/opt/airflow/dags
    - ./airflow_logs:/opt/airflow/logs
    - ./:/opt/airflow/
  user: "${AIRFLOW_UID:-50000}:0"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always


  webserver:
    <<: *airflow-common
    ports:
      - "8088:8088"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8088/health || exit 1"]
      interval: 10s
      retries: 5
    restart: always

  scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8088/health || exit 1"]
      interval: 10s
      retries: 5
    restart: always

  triggerer:
    <<: *airflow-common
    command: triggerer

  init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-aidf}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-aidf}

volumes:
  postgres-db-volume:

